#!/usr/bin/env python3
"""Prepare the public AS2000 bootstrap-diagnostic ROM files for MAME.

This script creates only independently authored test artifacts:
- as2k_stage0.bin
- as2k_bt8_dictrom.bin

It does NOT create, copy, or redistribute the stock AS2000 Z ROM.
"""

from pathlib import Path
import argparse
import hashlib
import zlib

STAGE0 = bytes.fromhex(
    "0F8E00C3143F04143C201500708604B74000153C80153C407E4000"
)
LANDING = bytes.fromhex(
    "864297A0865497A1863897A2862197A320FE"
)

EXPECTED = {
    "stage0_crc32": "ff5dedf9",
    "stage0_sha1": "ab76eafa386311b2ab70ea644345fb15767e908f",
    "stage0_sha256": "b46282c155c6656eb21cca8994213622e824e2619fa18d023ce5c108f35a4039",
    "dict_crc32": "c5bd89df",
    "dict_sha1": "6e84689da9e0705920bca24137c88a387dedfac1",
    "dict_sha256": "d76819d7f04b842a48cb3ed62ac4cd78fde9599bc9fdcf76fb704ea3850de4b4",
}


def crc32(data):
    return "%08x" % (zlib.crc32(data) & 0xffffffff)


def sha1(data):
    return hashlib.sha1(data).hexdigest()


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def verify(name, data, prefix):
    actual = {
        "crc32": crc32(data),
        "sha1": sha1(data),
        "sha256": sha256(data),
    }
    for algo, value in actual.items():
        expected = EXPECTED["%s_%s" % (prefix, algo)]
        if value != expected:
            raise SystemExit("%s %s mismatch: %s != %s" %
                             (name, algo, value, expected))
    return actual


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--romroot", default="roms")
    args = ap.parse_args()

    romdir = Path(args.romroot) / "asma2kbt"
    romdir.mkdir(parents=True, exist_ok=True)

    stage0 = STAGE0
    dictionary = bytearray([0xff]) * 0x20000
    dictionary[:len(LANDING)] = LANDING
    dictionary = bytes(dictionary)

    s = verify("stage0", stage0, "stage0")
    d = verify("dictrom", dictionary, "dict")

    (romdir / "as2k_stage0.bin").write_bytes(stage0)
    (romdir / "as2k_bt8_dictrom.bin").write_bytes(dictionary)

    print("Prepared", romdir)
    print("as2k_stage0.bin      size=%d CRC32=%s SHA1=%s" %
          (len(stage0), s["crc32"], s["sha1"]))
    print("as2k_bt8_dictrom.bin size=%d CRC32=%s SHA1=%s" %
          (len(dictionary), d["crc32"], d["sha1"]))
    print()
    print("Stock Z is NOT generated by this script.")
    print("Keep the normal asma2k parent ROM set available to MAME.")


if __name__ == "__main__":
    main()
